### ISSUE TITLE
Loft

### ISSUE THREAD

**Issue by jicowan** [kiosk-sh/kiosk#70]
This is less of an issue than a request for comment.  I see there's a pseudo-new solution call Loft, https://loft.sh.  Does it have any affiliation with Kiosk?

**Comment by LukasGentele** [comment]
Just like kiosk and [devspace](https://github.com/devspace-cloud/devspace), loft is also build by @FabianKramm 's and my team at DevSpace Technologies. We're a startup like many others in the cloud-native space. Unlike DevSpace and kiosk, loft is not open-source and represents the v2 of our commercial product called [DevSpace Cloud](https://devspace.cloud).

The initial idea for kiosk originated when we thought about building v2 of DevSpace Cloud which ended up being named loft to make clear that we are not a hosting service for Kubernetes. We thought that the multi-tenancy aspect of the our product is probably something others may need too, so we build it in a way that it could be used as a building block not just for loft but also for other projects and products. And then we open-sourced it as kiosk. This also ensures that we are eager to make a great project out of kiosk because our product is built on it and at the same time we hope that feedback, discourse and contributions from others will make it a better foundation for loft and other projects that may be build on top of kiosk.
