### ISSUE TITLE
Kiosk Prometheus Metrics

### ISSUE THREAD

**Issue by cbrgm** [kiosk-sh/kiosk#84]
Hi there,

are there any plans for adding prometheus metrics (accounts, spaces, quotasets)? Or do you have some recommendations for me how to monitor tenant resources?

Cheers
Chris

**Comment by FabianKramm** [comment]
@cbrgm thanks for opening this issue! We have a metrics endpoint on kiosk (although undocumented) at `:8080/metrics`. However these metrics are more performance centric on how kiosk is performing (latency, workqueue etc.) and not really about any resources it creates. We do not have any plans currently to add resource related metrics to kiosk, since I'm not really sure what metrics would be needed there.  

The easiest way to find out tenant resources is to group namespaces by label `kiosk.sh/account` and sum resources for the grouped namespaces. For more complex metrics I guess your best bet would be to write an own metrics server for kiosk or extend something like [kube-state-metrics](https://github.com/kubernetes/kube-state-metrics/tree/master/pkg) with your custom metrics that you need.

**Comment by cbrgm** [comment]
@FabianKramm thanks for the detailed reply!
