### ISSUE TITLE
Permanent template resources

### ISSUE THREAD

**Issue by d-m** [kiosk-sh/kiosk#91]
Is it possible to prevent the deletion of some template resources, or redeploy them automatically if they are deleted?

I'm thinking specifically of things like a NetworkPolicy object that prevents communication between Account namespaces. In the getting started documentation, the "John" user can delete the NetworkPolicy object created by the template when creating the "johns-space-template-mandatory" Space.

**Comment by LukasGentele** [comment]
@d-m you can use regular RBAC for this. In the `spec.space.clusterRole` of every Account (see "[Deletable Spaces](https://github.com/kiosk-sh/kiosk#35-create-deletable-spaces)" example in the readme). You can define the ClusterRole that kiosk uses to create the RoleBinding for the user to be able to manage resources in the namespaces created with this account. You can copy the kiosk default ClusterRole and change it so that users will not be able to manipulate NetworkPolicies.

Does that solve your issue?

**Comment by d-m** [comment]
Unfortunately no. We still want tenants to be able to manage their own NetworkPolicy objects since some need to be able to manage egress for their applications. I think we may end up looking at different SDN options for tenant isolation.

**Comment by FabianKramm** [comment]
@d-m you can still allow everything besides deleting NetworkPolicies via RBAC, but I guess in your case it would make sense to look at something like [gatekeeper](https://github.com/open-policy-agent/gatekeeper) or [kyverno](https://github.com/kyverno/kyverno) that allow you to define custom policies who can delete what in addition to what kiosk does.

**Comment by FabianKramm** [comment]
I'm closing this issue, since policies are not in the scope of kiosk and there are already other projects covering this.
